# Generated by Django 3.2.5 on 2024-04-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('cin', models.CharField(blank=True, max_length=20, null=True)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('télé', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
