# Generated by Django 3.2.5 on 2024-04-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi3smart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='produit',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('categorie', models.CharField(blank=True, max_length=150, null=True)),
                ('qteTotal', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
