# Generated by Django 3.2.5 on 2024-04-15 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bi3smart', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code_cate', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cate', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idCli', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCommande', models.AutoField(primary_key=True, serialize=False)),
                ('dateCommande', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('etatCommande', models.CharField(choices=[('A', 'Accepté'), ('R', 'Refusé'), ('EC ', 'En cours')], max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi3smart.client')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bi3smart.user'),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('idRec', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi3smart.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_commandee', models.IntegerField(blank=True, null=True)),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bi3smart.commande')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bi3smart.produit')),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi3smart.categorie'),
        ),
    ]
