# Generated by Django 3.2.5 on 2024-04-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi3smart', '0003_auto_20240415_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idAdmin',
            new_name='user_id',
        ),
    ]
