# Generated by Django 3.2.5 on 2024-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi3smart', '0004_rename_idadmin_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='télé',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
