# Generated by Django 3.2.5 on 2024-05-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi3smart', '0015_client_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etatCommande',
            field=models.CharField(choices=[('A', 'Accepté'), ('R', 'Refusé'), ('EC ', 'En cours')], default='EC', max_length=10),
        ),
    ]
