# Generated by Django 3.2.5 on 2024-05-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi3smart', '0016_alter_commande_etatcommande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='produit',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='nom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
