# Generated by Django 3.2.5 on 2024-05-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi3smart', '0017_auto_20240501_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='qte_commandee',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
